name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       sudo mkdir -p /mnt/ramdisk/centrex_controller
       sudo -u runner touch test /mnt/ramdisk/centrex_controller
       echo "adding runner into staff group"
       sudo usermod -aG staff runner
       sudo -u runner chown :staff /mnt/ramdisk/centrex_controller/test
       sudo ls -l /mnt/ramdisk/centrex_controller
     
