name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       # Set up the main directory
         sudo mkdir -p /mnt/ramdisk/centrex_controller
          
         sudo chown -R runner:docker /mnt/ramdisk/centrex_controller
         sudo setfacl -d -m g:docker:rwx /mnt/ramdisk/centrex_controller
         sudo chmod u+w /mnt/ramdisk/centrex_controller
     
         # Create a new subdirectory using the script
         sudo -u runner mkdir -p /mnt/ramdisk/centrex_controller/world
         
         # Check the permissions
         ls -la /mnt/ramdisk/centrex_controller

     
