name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
        sudo mkdir -p /mnt/ramdisk/centrex_controller
        sudo chown -R runner:staff /mnt/ramdisk/centrex_controller
        sudo setfacl -d -m g:staff:rwx /mnt/ramdisk/centrex_controller
        sudo chmod u+w /mnt/ramdisk/centrex_controller

        echo "Adding runner into staff group"
        sudo usermod -aG staff runner

        # Set the umask for the runner user
        echo "umask 002" | sudo -u runner tee -a $HOME/.bashrc
        source $HOME/.bashrc

        # Create a new directory
        sudo -u runner mkdir -p /mnt/ramdisk/centrex_controller/new_directory

        # Check the permissions
        ls -la /mnt/ramdisk/centrex_controller

     
