name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       # Set up the main directory
         sudo mkdir -p /mnt/ramdisk/centrex_controller
          
         sudo chown -R runner:docker /mnt/ramdisk/centrex_controller
         sudo setfacl -d -m g:docker:rwx /mnt/ramdisk/centrex_controller
         sudo chmod u+w /mnt/ramdisk/centrex_controller
         
         
         
         # Set the umask for the 'runner' user
         sudo -u runner bash -c 'echo "umask 002" >> ~/.bashrc'
         
         # Activate the new umask for the current session
         source /home/runner/.bashrc
         
         # Create a new subdirectory using the script
         sudo -u runner mkdir -p /mnt/ramdisk/centrex_controller/new_dir
         
         # Check the permissions
         ls -la /mnt/ramdisk/centrex_controller

     
