name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       mkdir -p /mnt/ramdisk/centrex 
       chmod -R 777 /mnt/ramdisk
       ls -la /mnt/ramdisk
