name: centrx-controler testcases

on: [push, pull_request]

jobs:
 
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: 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
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libyaml-dev
        gem install bundler
        bundle install --without production

    - name: Install MariaDB
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo systemctl stop mysql
        sudo mysqld --socket=/tmp/mysql.sock > /dev/null 2>&1 &

    - name: Additional Setup
      run: |
        sudo mkdir /mnt/ramdisk
        sudo mount -t tmpfs -o size=1000m tmpfs /mnt/ramdisk
        sudo df -h | grep mnt
        sudo mkdir -p /mnt/ramdisk/mariadb
        sudo chown -R mysql:mysql /mnt/ramdisk/mariadb
        sudo /usr/bin/mysql_install_db --user=mysql --basedir="/usr/" --datadir=/mnt/ramdisk/mariadb
        sudo systemctl restart mariadb
        sudo mysql -S /tmp/mysql.sock  --execute "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');"
        mysqladmin -u root --socket=/tmp/mysql.sock ping

    - name: Install Redis
      run: |
        sudo apt update
        sudo apt install -y redis-server
        sudo systemctl stop redis-server
        
    - name: Run Redis Server in the Background
      run: |
        redis-server --notify-keyspace-events KEA --unixsocket /tmp/redis.sock --unixsocketperm 777 &
        sleep 5  # Allow some time for Redis to start

    - name: Check Redis Server Status
      run: |
        redis-cli -s /tmp/redis.sock ping
