name: centrx-controler testcases

on: [push, pull_request]

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install MariaDB
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo systemctl start mariadb
        sudo systemctl enable mariadb
        sudo mysql -v
        ls -la /etc/mysql || true
        ls -la /etc/mysql/mariadb.conf.d ||true
    - name: Install Redis
      run: |
        sudo apt update
        sudo apt install -y redis-server
        sudo systemctl stop redis-server
        
    - name: Run Redis Server in the Background
      run: |
        redis-server --notify-keyspace-events KEA --unixsocket /tmp/redis.sock --unixsocketperm 777 &
        sleep 5  # Allow some time for Redis to start

    - name: Check Redis Server Status
      run: |
        redis-cli -s /tmp/redis.sock ping
