name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       sudo mkdir -p /mnt/ramdisk/centrex_controller
       sudo chown -R runner:staff /mnt/ramdisk/centrex_controller
       sudo -u runner touch /mnt/ramdisk/centrex_controller/test
       echo "adding runner into staff group"
       sudo usermod -aG staff runner
       sudo chmod -R g+w /mnt/ramdisk/centrex_controller
       sudo -u runner chown -R :staff /mnt/ramdisk/centrex_controller
       sudo ls -l /mnt/ramdisk/centrex_controller
       sudo -u runner mkdir -p /mnt/ramdisk/centrex_controller/hello
       ls -la /mnt/ramdisk/centrex_controller
     
