name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
        sudo cat /etc/group
        echo "$USER"
        groups "$USER"
