name: centrx-controler testcases

on: 
 push:

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checking groups
      run: |
       sudo mkdir -p /mnt/ramdisk/centrex
       sudo chmod -R 777 /mnt/ramdisk
       ls -la /mnt/ramdisk
