name: centrx-controler testcases

on: [push, pull_request]

jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Redis
      run: |
        sudo apt update
        sudo apt install -y redis-server
        sudo systemctl stop redis-server
        
    - name: Run Redis Server in the Background
      run: |
        redis-server --notify-keyspace-events KEA --unixsocket /tmp/redis.sock --unixsocketperm 777 &
        sleep 5  # Allow some time for Redis to start

    - name: Check Redis Server Status
      run: |
        redis-cli -s /tmp/redis.sock ping
