name: testcases

on: 
  push

jobs:
 tests:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      run: |
        echo "2959 specifications (9270 requirements), 3 failures, 0 errors" >> output.txt
        cat output.txt
        failures_count=$(awk -F ', ' '{print $2}' output.txt | awk '{print $1}')
        echo "failures_count=${failures_count}" >> $GITHUB_ENV
        echo "${{ env.failures_count }}"
